/**
 * Enum containing all environment variable keys
 * This provides type safety when accessing environment variables
 */
export enum ConfigKeys {
  // API Documentation
  APP_DOCUMENTATION_TITLE = 'APP_DOCUMENTATION_TITLE',
  APP_DOCUMENTATION_DESCRIPTION = 'APP_DOCUMENTATION_DESCRIPTION',
  VERSION = 'VERSION',
  ENVIRONMENT = 'ENVIRONMENT',
  SWAGGER_DOCUMENT_URL = 'SWAGGER_DOCUMENT_URL',

  // Server
  PORT = 'PORT',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',
  API_SECRET = 'API_SECRET',

  // Authentication
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
  JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET_KEY',
  JWT_REFRESH_EXPIRATION_TIME = 'JWT_REFRESH_EXPIRATION_TIME',

  // Auth Cookies
  COOKIE_SECRET = 'COOKIE_SECRET',
  COOKIE_NAME = 'COOKIE_NAME',
  COOKIE_DOMAIN = 'COOKIE_DOMAIN',
  COOKIE_HTTP_ONLY = 'COOKIE_HTTP_ONLY',
  COOKIE_SECURE = 'COOKIE_SECURE',
  COOKIE_SAME_SITE = 'COOKIE_SAME_SITE',
  COOKIE_PATH = 'COOKIE_PATH',
  COOKIE_MAX_AGE = 'COOKIE_MAX_AGE',
  REFRESH_TOKEN_EXPIRATION = 'REFRESH_TOKEN_EXPIRATION',

  // Database - Shopilama
  SHOP_HOST = 'SHOP_HOST',
  SHOP_PORT = 'SHOP_PORT',
  SHOP_USERNAME = 'SHOP_USERNAME',
  SHOP_PASSWORD = 'SHOP_PASSWORD',
  SHOP_DATABASE = 'SHOP_DATABASE',

  // Database - Intranet
  HOST_INTRANET = 'HOST_INTRANET',
  PORT_INTRANET = 'PORT_INTRANET',
  USERNAME_INTRANET = 'USERNAME_INTRANET',
  PASSWORD_INTRANET = 'PASSWORD_INTRANET',
  DATABASE_INTRANET = 'DATABASE_INTRANET',

  // Database - Oracle
  ORACLE_USERNAME = 'ORACLE_USERNAME',
  ORACLE_PASSWORD = 'ORACLE_PASSWORD',
  DBLINK = 'DBLINK',
  ORACLE_CONNSTRING = 'ORACLE_CONNSTRING',

  // External Services
  INTRANET_API_BASE_URL = 'INTRANET_API_BASE_URL',
  SHOPILAMA_API_BASE_URL = 'SHOPILAMA_API_BASE_URL',
  ECOMMERCE_INSTALEAP_API_BASE_URL = 'ECOMMERCE_INSTALEAP_API_BASE_URL',
  PTLOG_API_BASE_URL = 'PTLOG_API_BASE_URL',

  // Cloudflare
  BASE_CLOUDFLARE_IMG = 'BASE_CLOUDFLARE_IMG',
  CLOUDFLARE_BASE_URL = 'CLOUDFLARE_BASE_URL',
  CLOUDFLARE_ACCOUNT_ID = 'CLOUDFLARE_ACCOUNT_ID',
  CLOUDFLARE_API_TOKEN = 'CLOUDFLARE_API_TOKEN',
  CLOUDFLARE_IMAGE_DNS = 'CLOUDFLARE_IMAGE_DNS',
  CLOUDFLARE_IMAGE_PREFIX = 'CLOUDFLARE_IMAGE_PREFIX',

  // ChatGPT API
  CHAT_GPT_API_KEY = 'CHAT_GPT_API_KEY',
  CHAT_GPT_BASE_URL = 'CHAT_GPT_BASE_URL',

  // Instaleap API
  INSTALEAP_API_KEY = 'INSTALEAP_API_KEY',
  INSTALEAP_API_BASE_URL = 'INSTALEAP_API_BASE_URL',
}
