/**
 * Enum containing all environment variable keys
 * This provides type safety when accessing environment variables
 */
export enum ConfigKeys {
  // API Documentation
  APP_DOCUMENTATION_TITLE = 'APP_DOCUMENTATION_TITLE',
  APP_DOCUMENTATION_DESCRIPTION = 'APP_DOCUMENTATION_DESCRIPTION',
  VERSION = 'VERSION',
  ENVIRONMENT = 'ENVIRONMENT',
  SWAGGER_DOCUMENT_URL = 'SWAGGER_DOCUMENT_URL',

  // Server
  PORT = 'PORT',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',
  API_SECRET = 'API_SECRET',

  // Authentication
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',

  // Database - Shopilama
  SHOP_HOST = 'SHOP_HOST',
  SHOP_PORT = 'SHOP_PORT',
  SHOP_USERNAME = 'SHOP_USERNAME',
  SHOP_PASSWORD = 'SHOP_PASSWORD',
  SHOP_DATABASE = 'SHOP_DATABASE',

  // Database - Secondary
  HOST_36 = 'HOST_36',
  USERNAME_36 = 'USERNAME_36',
  PASSWORD_36 = 'PASSWORD_36',
  DATABASE_36 = 'DATABASE_36',

  // Database - Oracle
  ORACLE_USERNAME = 'ORACLE_USERNAME',
  ORACLE_PASSWORD = 'ORACLE_PASSWORD',
  DBLINK = 'DBLINK',
  ORACLE_CONNSTRING = 'ORACLE_CONNSTRING',

  // External Services
  INTRANET = 'INTRANET',
  INSTALEAP_API_BASE_URL = 'INSTALEAP_API_BASE_URL',
  INSTALEAP_API_KEY = 'INSTALEAP_API_KEY',
  E_COMMERCE_INSTALEAP = 'E_COMMERCE_INSTALEAP',
  CLOUDFLARE = 'CLOUDFLARE',
  URL_CLOUDFLARE_SUFFIX = 'URL_CLOUDFLARE_SUFFIX',
  BASE_CLOUDFLARE_IMG = 'BASE_CLOUDFLARE_IMG',
  PTLOG_BASE_URL = 'PTLOG_BASE_URL',

  // Third-party APIs
  CHAT_GPT_API_KEY = 'CHAT_GPT_API_KEY',
  CHAT_GPT_URL = 'CHAT_GPT_URL',
}
